comments = [ 
'This was a splendid review',
'I am definetly getting This phone',
'The specs are ok but not good enough',
'This is really an expensive phone',
'I wish i could get this phone',
'This is actually quite a bargain',
'I am interested in gettng this phone',
'I hope this phone lasts well',
'I have been hearing that phones like this have bad quality control',
'This phone costs a fortune',
'I wonder if it will run COD properly',
'This seems very promising to say the least',
'Hopefully i should be able to afford this',
'This seems like a very beefy phone',
'I like the critical and technical reviews of this site',
'I am very impressed with this post',
'I will refer more people to this site',
'I appreciate the initiative of this site',
'A very compelling and descriptive review',
'I like this project',
'A very wonderful review post',

]